version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-fastapi
    hostname: backend-fastapi
    volumes:
      - ./backend:/app
    ports:
      - "8088:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-react
    hostname: frontend-react
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"
    environment:
      - VITE_OKTA_CLIENT_ID=0oapbmvtyyl2qb7Dv697
      - VITE_OKTA_ISSUER=https://ltv.puzzle.sg
      - VITE_OKTA_REDIRECT_URI=https://ltv.puzzle.sg/login/callback

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Sử dụng Dockerfile.dev cho môi trường dev
    container_name: frontend-react-dev
    hostname: frontend-react-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3003:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_OKTA_CLIENT_ID=0oapbmvtyyl2qb7Dv697
      - VITE_OKTA_ISSUER=https://login.puzzle.sg
      - VITE_OKTA_REDIRECT_URI=http://localhost:3001/login/callback
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3001"]
