version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-fastapi
    hostname: backend-fastapi
    volumes:
      - ./backend:/app
    ports:
      - "8088:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-react
    hostname: frontend-react
    volumes:
      - ./frontend:/app
    ports:
      - "3003:80"  # Không cần publish 80/443 ra ngoài
    environment:
      - VITE_OKTA_CLIENT_ID=0oapbmvtyyl2qb7Dv697
      - VITE_OKTA_ISSUER=https://login.puzzle.sg
      - VITE_OKTA_REDIRECT_URI=https://ltv.puzzle.sg/login/callback
