export const PartnerList = [
    { value: "3DOT14 PROGRAMMATIC" },
    { value: "3DOT14_PROGRAMMATIC" },
    { value: "ADACTION" },
    { value: "ADACTION INTERACTIVE" },
    { value: "ADACTION INTERACTIVE CPE" },
    { value: "ADCOLONY" },
    { value: "ADGATE" },
    { value: "ADGATE MEDIA" },
    { value: "ADJOE" },
    { value: "ADSCEND MEDIA" },
    { value: "ADWORDS" },
    { value: "APP SAMURAI" },
    { value: "APPLE SEARCH ADS" },
    { value: "APPLOVIN" },
    { value: "AUDIOMOB" },
    { value: "AURA" },
    { value: "AURA IRONSOURCE" },
    { value: "AYET-STUDIOS" },
    { value: "BLOCKGAMES" },
    { value: "CHARTBOOST" },
    { value: "CROSSPROMO (CUSTOM)" },
    { value: "FACEBOOK" },
    { value: "FYBER" },
    { value: "GOOGLE ADWORDS FOR VIDEO - UAC" },
    { value: "GOOGLE DISPLAY - UAC" },
    { value: "GOOGLE SEARCH - UAC" },
    { value: "GREE ADS REWARD" },
    { value: "GREEDYGAME MEDIA" },
    { value: "GREEDYGAMES ADMON" },
    { value: "HANG MY ADS" },
    { value: "IMPORTED USERS" },
    { value: "IOS SEARCH ADS" },
    { value: "IRONSOURCE" },
    { value: "MINTEGRAL INTERNATIONAL LIMITED" },
    { value: "MISTPLAY" },
    { value: "MOBISUMMER" },
    { value: "MOBUPPS" },
    { value: "MOBUPPS CPA" },
    { value: "MOTIVE INTERACTIVE" },
    { value: "MOTIVE INTERACTIVE SECONDARY" },
    { value: "OFFERTORO" },
    { value: "ORGANIC" },
    { value: "PRODEGE" },
    { value: "PUBSCALE" },
    { value: "REVENUE UNIVERSE" },
    { value: "REVENUE_UNIVERSE" },
    { value: "SKY FLAG" },
    { value: "SKYFLAG" },
    { value: "SMAAD" },
    { value: "SMAAD CPE" },
    { value: "SMAAD_CPE" },
    { value: "SOCIAL (CUSTOM)" },
    { value: "TAPJOY" },
    { value: "TAPTICA" },
    { value: "TIKTOK" },
    { value: "TIKTOK ADS" },
    { value: "TIKTOK ADS RESTRICTED" },
    { value: "TIKTOK RESTRICTED" },
    { value: "TOROX.IO" },
    { value: "TYRADS" },
    { value: "UNATTRIBUTED" },
    { value: "UNITY ADS" },
    { value: "UNKNOWN" },
    { value: "VUNGLE" },  
  ];
